### ISSUE TITLE
File written to is blank

### ISSUE THREAD

**Issue by CoelacanthsKill** [JackFrancisD/pyApolloPhotosDownloader#3]
An empty file is created when using Windows 7 64bit, Python 3.5.1

**Comment by Kickball** [comment]
Were any errors thrown by the program?

Does your user have the proper permissions for that folder?

Was your computer disconnected from the internet at the time, or having any troubles?

Are you referencing 'photolinks.lst'?

You haven't give us much information here.

**Comment by CoelacanthsKill** [comment]
Yes, running as root.
No errors, acts like it ran normally.
Yes, photolinks.lst.

**Comment by Kickball** [comment]
Try adding:

`print_r(finalLinksList)`

on line 92 at the same indentation level as the return and see what is printed to your console. This will help us figure out if the problem is with the scraping of the site or the writing to the file.

**Comment by CoelacanthsKill** [comment]
# Coded by JackFrancisD jackfd@openmailbox.org

[!] This software is an early version. No errors are handled, but it does
work.
[_] Starting Flickr direct link extraction from
https://www.flickr.com/photos/na
sahqphoto
[_] Extracting page count...
[_] 103 pages found.
[_] Extracting direct links from page 1...
Traceback (most recent call last):
  File "pyApolloDL.py", line 129, in <module>
    main()
  File "pyApolloDL.py", line 122, in main
    getAllLinks()
  File "pyApolloDL.py", line 92, in getAllLinks
    print_r(finalLinksList)
NameError: name 'print_r' is not defined

**Comment by Kickball** [comment]
My apologies I got confused with PHP functions.

Please replace the print_r with:

```
print finalLinksList
```
